clear all
clc
art = load('C:\Users\12517\Desktop\paper3\MS1\art-obj.mat');
bird = load('C:\Users\12517\Desktop\paper3\MS1\bird-obj.mat');
computer = load('C:\Users\12517\Desktop\paper3\MS1\computer-obj.mat');
education = load('C:\Users\12517\Desktop\paper3\MS1\education-obj.mat');
emotion = load('C:\Users\12517\Desktop\paper3\MS1\emotion-obj.mat');
genbase = load('C:\Users\12517\Desktop\paper3\MS1\genbase-obj.mat');
image = load('C:\Users\12517\Desktop\paper3\MS1\image-obj.mat');
medical = load('C:\Users\12517\Desktop\paper3\MS1\medical-obj.mat');
recreation = load('C:\Users\12517\Desktop\paper3\MS1\recreation-obj.mat');
science = load('C:\Users\12517\Desktop\paper3\MS1\science-obj.mat');
slashdot = load('C:\Users\12517\Desktop\paper3\MS1\slashdot-obj.mat');
yeast = load('C:\Users\12517\Desktop\paper3\MS1\yeast-obj.mat');

artobj = art.obj;
birdobj = bird.obj;
computerobj = computer.obj;
educationobj = education.obj;
emotionobj = emotion.obj;
genbaseobj = genbase.obj;
imageobj = image.obj;
medicalobj = medical.obj;
recreationobj = recreation.obj;
scienceobj = science.obj;
slashdotobj = slashdot.obj;
yeastobj = yeast.obj;

x= [1:10];
figure;
plot(x,artobj(:,2:11),'r-x','LineWidth',1.5);
hold on;
title('arts','FontSize',12);
ga1 = legend('Ours');
xlabel('Number of iterations','FontSize',12,'FontName','Arial');
ylabel('Objective function value','FontSize',12,'FontName','Arial');
hold off;
figure;
plot(x,birdobj(:,2:11),'r-x','LineWidth',1.5);
hold on;
title('birds','FontSize',12);
ga2 = legend('Ours');
xlabel('Number of iterations','FontSize',12,'FontName','Arial');
ylabel('Objective function value','FontSize',12,'FontName','Arial');
hold off;
figure;
plot(x,computerobj(:,2:11),'r-x','LineWidth',1.5);
hold on;
title('computer','FontSize',12);
ga3 = legend('Ours');
xlabel('Number of iterations','FontSize',12,'FontName','Arial');
ylabel('Objective function value','FontSize',12,'FontName','Arial');
hold off;
figure;
plot(x,educationobj(:,2:11),'r-x','LineWidth',1.5);
hold on;
title('education','FontSize',12);
ga4 = legend('Ours');
xlabel('Number of iterations','FontSize',12,'FontName','Arial');
ylabel('Objective function value','FontSize',12,'FontName','Arial');
hold off;
figure;
plot(x,emotionobj(:,2:11),'r-x','LineWidth',1.5);
hold on;
title('emotion','FontSize',12);
ga5 = legend('Ours');
xlabel('Number of iterations','FontSize',12,'FontName','Arial');
ylabel('Objective function value','FontSize',12,'FontName','Arial');
hold off;
figure;
plot(x,genbaseobj(:,2:11),'r-x','LineWidth',1.5);
hold on;
title('genbase','FontSize',12);
ga6 = legend('Ours');
xlabel('Number of iterations','FontSize',12,'FontName','Arial');
ylabel('Objective function value','FontSize',12,'FontName','Arial');
hold off;
figure;
plot(x,imageobj(:,2:11),'r-x','LineWidth',1.5);
hold on;
title('image','FontSize',12);
ga7 = legend('Ours');
xlabel('Number of iterations','FontSize',12,'FontName','Arial');
ylabel('Objective function value','FontSize',12,'FontName','Arial');
hold off;
figure;
plot(x,medicalobj(:,2:11),'r-x','LineWidth',1.5);
hold on;
title('medical','FontSize',12);
ga8 = legend('Ours');
xlabel('Number of iterations','FontSize',12,'FontName','Arial');
ylabel('Objective function value','FontSize',12,'FontName','Arial');
hold off;
figure;
plot(x,recreationobj(:,2:11),'r-x','LineWidth',1.5);
hold on;
title('recreation','FontSize',12);
ga9 = legend('Ours');
xlabel('Number of iterations','FontSize',12,'FontName','Arial');
ylabel('Objective function value','FontSize',12,'FontName','Arial');
hold off;
figure;
plot(x,scienceobj(:,2:11),'r-x','LineWidth',1.5);
hold on;
title('science','FontSize',12);
ga10 = legend('Ours');
xlabel('Number of iterations','FontSize',12,'FontName','Arial');
ylabel('Objective function value','FontSize',12,'FontName','Arial');
hold off;
figure;
plot(x,slashdotobj(:,2:11),'r-x','LineWidth',1.5);
hold on;
title('slashdot','FontSize',12);
ga11 = legend('Ours');
xlabel('Number of iterations','FontSize',12,'FontName','Arial');
ylabel('Objective function value','FontSize',12,'FontName','Arial');
hold off;
figure;
plot(x,yeastobj(:,2:11),'r-x','LineWidth',1.5);
hold on;
title('yeast','FontSize',12);
ga12 = legend('Ours');
xlabel('Number of iterations','FontSize',12,'FontName','Arial');
ylabel('Objective function value','FontSize',12,'FontName','Arial');
hold off;